version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: web_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install mysqli && 
      apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    