source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 7.0.4'
gem 'puma', '~> 5.0'
gem 'pg', '~> 1.4'
gem 'bootsnap', require: false
gem 'sassc-rails'
gem 'image_processing', '~> 1.2'
gem 'jsbundling-rails'
gem 'cssbundling-rails'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
end